#!/bin/bash
export GIT_PS1_SHOWCOLORHINTS=1
export GIT_PS1_SHOWDIRTYSTATE=1
. /home/trevor/devel/extern/git/contrib/completion/git-completion.bash
. /home/trevor/devel/extern/git/contrib/completion/git-prompt.sh

for s in /home/trevor/local/etc/bash_completion.d/*.sh ; do
	test -r $s && . $s
done
